CONNECT SYS AS SYSDBA
CREATE SPFILE FROM PFILE = 'initGubarevVladimirP3401.ora';
STARTUP NOMOUNT;
CREATE DATABASE easymeat
	CHARACTER SET UTF8
	NATIONAL CHARACTER SET UTF8
	DATAFILE '/u01/neb87/easymeat/node03/ebaxo22.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	         '/u01/neb87/easymeat/node01/uzase61.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	         '/u01/neb87/easymeat/node02/okiye81.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	SYSAUX DATAFILE '/u01/neb87/easymeat/node03/rit71.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	                '/u01/neb87/easymeat/node04/yuf7.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	UNDO TABLESPACE undotbs1 DATAFILE '/u01/neb87/easymeat/undo.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	DEFAULT TABLESPACE users DATAFILE '/u01/neb87/easymeat/node04/eqexofe831.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	                                  '/u01/neb87/easymeat/node03/omoxoye753.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE TABLESPACE FAST_GOLD_ROAD datafile 
	'/u01/neb87/easymeat/node01/fastgoldroad01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
	'/u01/neb87/easymeat/node04/fastgoldroad02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
	'/u01/neb87/easymeat/node02/fastgoldroad03.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE LEFT_BLACK_FOOD datafile 
	'/u01/neb87/easymeat/node01/leftblackfood01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
	'/u01/neb87/easymeat/node01/leftblackfood02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
@?/rdbms/admin/catalog.sql
@?/rdbms/admin/catproc.sql
EXIT
